"""Account password

Revision ID: 33c729facbad
Revises: f420b4b2f4aa
Create Date: 2025-04-12 21:48:35.427085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33c729facbad'
down_revision = 'f420b4b2f4aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'password')
    # ### end Alembic commands ###
